version: '3.2'
services:
  postgres:
    image: postgres
    ports:
      - "5434:5432"
  simple-run-service:
    image: alagiz/simple-run-service:latest
    entrypoint: ["java", "-jar", "/app.jar"]
    environment:
      - POSTGRES_URL=postgres:5432
    ports:
      - "8082:8080"
